/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/api/public/bootstrap' | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/public/bootstrap' | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/bootstrap'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
